### ISSUE TITLE
Add new property into label button 

### ISSUE THREAD

**Issue by malikdoksoz** [jaweii/Flutter_beautiful_popup#1]
Can you add labelStyle into popup.button. (with TextStyle class)

> popup.button(
>                       label: 'Go Home',
>                       **labelStyle: TextStyle(fontSize: 20),**
>                       onPressed: Navigator.of(context).pop,
>                       outline: false),
>                 ]);

**Comment by jaweii** [comment]
I think you can replace the popup.button with a wiget like MaterialButton/CupertinoButton.

**Comment by jaweii** [comment]
Supported in new version.

**Comment by malikdoksoz** [comment]
You can add in Common.dart, label style property.

> typedef Widget BeautifulPopupButton({
  @required String label,
  **TextStyle labelStyle,**
  @required void Function() onPressed,
  bool outline,
});
