### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by nowfalsalahudeen** [jaweii/Flutter_beautiful_popup#13]
Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../development/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
                Theme.of(options.context).textTheme.subhead?.fontSize ?? 12,

**Comment by jaweii** [comment]
Try the new version 1.7.0
