### ISSUE TITLE
Want to know images

### ISSUE THREAD

**Issue by rupamking1** [jaweii/Flutter_beautiful_popup#8]
Please tell me about images you used in your packages, I want to use in my app but not in popup, Can you tell me from where you downloaded this images?

**Comment by jaweii** [comment]
I collected them from several websites, you can try to use Google Images "App Popup Design".




------------------ Original ------------------

**Comment by arreyazat** [comment]
> I collected them from several websites, you can try to use Google Images "App Popup Design".
> […](#)
> ------------------ Original ------------------ From: rupamking1 <notifications@github.com&gt; Date: Mon,Jan 11,2021 4:38 AM To: jaweii/Flutter_beautiful_popup <Flutter_beautiful_popup@noreply.github.com&gt; Cc: Subscribed <subscribed@noreply.github.com&gt; Subject: Re: [jaweii/Flutter_beautiful_popup] Want to know images (#8) Please tell me about images you used in your packages, I want to use in my app but not in popup, Can you tell me from where you downloaded this images? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I assume that the images are not available when imported?

`======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/flutter_beautiful_popup/img/bg/gift.png

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:225:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:668:31)
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:651:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:504:13)
...
Image provider: AssetImage(bundle: null, name: "packages/flutter_beautiful_popup/img/bg/gift.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#ee572(), name: "packages/flutter_beautiful_popup/img/bg/gift.png", scale: 1.0)
====================================================================================================
`
